### ISSUE TITLE
Loading course home when courses' date is in the future fails

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/frontend-app-learning#1240] opened 2023-11-22 18:13 UTC
### Description
After creating a new course in my nightly installation, and then trying to view it live the learning MFE fails:

[Screencast from 22-11-23 14:09:38.webm](https://github.com/openedx/frontend-app-learning/assets/64440265/b00603cc-6be2-419e-bb33-6dd568ad22df)

This was also reported by a quince release tester: https://github.com/openedx/wg-build-test-release/issues/319
When changing the course start date from Studio the error disappears. 

### How to reproduce
1. Create a new course using quince or tutor nightly
2. View course live
3. Try accessing: `HTTP(s)://<MFE_HOST>/learning/course/<COURSE_ID>/home`

**Comment by pdpinch** [comment] 2023-11-27 15:37
We (MIT Open Learning) haven't been able to reproduce this issue in our two test environments. I'm still trying to confirm which commits of edx-platform and the learning MFE we are using.

**Comment by arbrandes** [comment] 2023-12-06 21:44
This is not a bug in the Learning MFE itself, but rather in `frontend-platform` or `tutor-mfe`, depending on perspective.  For now we fix it in `tutor-mfe`, as a recent change in that line is what revealed the symptom.

https://github.com/overhangio/tutor-mfe/pull/173

Closing this in favor of the existing BTR issues.

**Closed as completed by arbrandes** 2023-12-06 21:44 UTC
Labels: bug
